### ISSUE TITLE
Python 2.7 Support

### ISSUE THREAD

**Issue by tslater** [aws/aws-lambda-python-runtime-interface-client#4]
I know Python 2.7 is uhhh....dead, but I have a complex legacy application (that still has state of the art results for an ML task) that I'd like to run on Lambda. I thought that increased docker support for Lambda could be a good way out since It's likely to be pulled from normal runtimes. Would be nice to park legacy support here.

**Comment by carlzogh** [comment]
Hey @tslater - thanks for reaching out!

We made the decision here to not support Python 2.7 as it's been EOL for almost a year now. We still support Python 2.7 as a managed Lambda runtime because Amazon Linux has taken ownership of patches, but we cannot guarantee that consumers of this library will benefit from these patches and adding support for Python 2.7 for a new library feels like a step in the wrong direction.

This said if you wanted to run this library with Python 2.7, my best recommendation at this point is to fork the repository and make the required changes you need to get it up and running with the runtime version you wish to use it with. All the major building blocks are there, I don't believe there are many significant code changes to be done to support this.

Apologies if this was not the answer you were after, but for the sake of your application's security and maintainability (and I truly appreciate how complex this can be - we've been though this ourselves!) I recommend (maybe even _urge_) you to try and migrate your application to a modern version of the runtime. I've found there are numerous helpful articles and tools out there to help out with this (a few links below). As Python 2.7 is slowly but surely fading away, production application developers _really_ need to consider investing some time in a migration strategy.

Otherwise another alternative I could suggest would be to grab a copy of the AWS Lambda Python 2.7 base image available as `public.ecr.aws/lambda/python:2.7` (check out https://gallery.ecr.aws/lambda/python and [AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/python-image.html)) for a good starting point) and package your function as a container image if a migration to Python 3 or a fork of the Runtime Interface Client seem too daunting.

Please feel free to reach out to our support team if you require assistance with your application. Best of luck!


Python 2 -> 3 migration:
- https://docs.python.org/3/howto/pyporting.html
- https://scoutapm.com/blog/automated-tools-and-strategies-to-help-migrate-from-python-2-to-3
