### ISSUE TITLE
Feature request: allow lambda to make external IPv6 request

### ISSUE THREAD

**Issue by tyjaon** [aws/aws-lambda-python-runtime-interface-client#50]
I would like to ask you to allow lambda to make external IPv6 requests. Probably in near feature a lot of people will face a lack of sending request from lambda to external IPv6  that is why I'm requesting it. 

I'm including also my previous ticket   #49 @ in case if someone will be looking for this kind of topic.

**Comment by reku47** [comment]
i would like the same 🏳️‍🌈🏳️‍🌈

**Comment by maciejbial** [comment]
Please consider this request IPv6 is a standard it should be supported.

**Comment by carlzogh** [comment]
Thanks @tyjaon - I have communicated this to the right folks internally and it is being tracked as a feature request. 

This repository however is not the right owner for this feature request, so I'll go ahead and close this issue here but please rest assured that your and others' feedback has been duly noted.

Thanks again all :)
